name: Deploy

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
      steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: "pnpm"
        - name: Use Fly.io
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Install dependencies
          run: pnpm install
        - name: Build web
          run: pnpm --filter=@dnd-demo/web build
        - name: Deploy server
          run: flyctl deploy --remote-only
        - name: Deploy web
          run: pnpm --filter=@dnd-demo/web deploy
